"""fix updated_at default

Revision ID: 342a5d6e5660
Revises: a449bb8af104
Create Date: 2025-08-22 17:33:45.996024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342a5d6e5660'
down_revision: Union[str, Sequence[str], None] = 'a449bb8af104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text('NOW()'),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
        existing_nullable=False
    )
    # ### end Alembic commands ###
