"""create summary_report table

Revision ID: 90d9b518552d
Revises: cfc26a2b70e9
Create Date: 2025-09-19 17:13:03.903962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d9b518552d'
down_revision: Union[str, Sequence[str], None] = 'cfc26a2b70e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('total_test_items', sa.Integer(), nullable=True),
    sa.Column('total_test_implementations', sa.Integer(), nullable=True),
    sa.Column('total_non_implementations', sa.Integer(), nullable=True),
    sa.Column('overall_coverage', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_reports_id'), 'summary_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_reports_id'), table_name='summary_reports')
    op.drop_table('summary_reports')
    # ### end Alembic commands ###
