"""update case requirements

Revision ID: b0f0812f19b7
Revises: fbb9722a0b4b
Create Date: 2025-09-09 12:17:27.798514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f0812f19b7'
down_revision: Union[str, Sequence[str], None] = 'fbb9722a0b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('requirement_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('cases_project_id_fkey'), 'cases', type_='foreignkey')
    op.create_foreign_key(None, 'cases', 'requirements', ['requirement_id'], ['id'])
    op.drop_column('cases', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_foreign_key(op.f('cases_project_id_fkey'), 'cases', 'projects', ['project_id'], ['id'])
    op.drop_column('cases', 'requirement_id')
    # ### end Alembic commands ###
